[package]
name = "client"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
quinn.workspace = true
rcgen.workspace = true
lib.workspace = true
tokio.workspace = true
rkyv.workspace = true
rayon.workspace = true
walkdir.workspace = true
bytes.workspace = true
tracing.workspace = true
bit-set.workspace = true
